spring:
  datasource:
    url: jdbc:mysql://114.67.91.251:3306/pdf?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    db-name: pdf
    filters: log4j,wall,mergeStat
    mvc:
      static-path-pattern: /static/**
      view:
        prefix: /templates
      locale: zh_CN


server:
  port: 7081

mybatis-plus:
  type-aliases-package: com.example.pdf.entity
  mapper-locations: classpath*:com/example/pdf/**/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

